spring:
  application:
    name: Spring-AI
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_memory_db
    username: postgres
    password: ShivamJha91
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      api-key: ${AZURE_OPENAI_API_KEY}
      base-url: ${AZURE_OPENAI_BASE_URL}
      chat:
        model: gpt-5.6-sol-2
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

elevenlabs:
  api-key: ${ELEVENLABS_API_KEY:sk_4f754ca1dd4cdb6a3d375147e1931d5c5a0c4fa08f3f19c2}
  voice-id: ${ELEVENLABS_VOICE_ID:IKne3meq5aSn9XLyUdCD}

logging:
  level:
    org:
      springframework:
        ai: TRACE

